export const ADD_MOVIE_START = "ADD_MOVIE_START";
export const REMOVE_MOVIE_START = "REMOVE_MOVIE_START";
export const FETCH_MOVIES_LIST_START = "FETCH_MOVIES_LIST_START";
export const STORE_MOVIES = "STORE_MOVIES";
